version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-local
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama # Store models in project folder
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    # Uncomment if you have GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # app:
  #   build: ./app
  #   container_name: llama3-app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - ollama
  #   environment:
  #     - OLLAMA_BASE_URL=http://ollama:11434
  #   volumes:
  #     - ./app:/app
  #   working_dir: /app
